## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
 allow_failures:
 - julia: nightly

## uncomment and modify the following lines to manually install system packages
addons:
    apt:
        packages:
            - xvfb
            - xauth
            - libgtk-3-0
              # - if [ $TRAVIS_OS_NAME = osx ]; then brew install libgtk-3-0; fi
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
# script:
    # - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    # - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
    # - $TESTCMD -e 'Pkg.clone(pwd()); using BinDeps;
    #     println(BinDeps.debug("Scallop"));
    #     Pkg.build("Scallop");
    #     Pkg.test("Scallop"; coverage=true)'
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Scallop"); Pkg.test("Scallop"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("Scallop")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Scallop")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
